AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Telegram AI Summary Bot
  
  A serverless application that helps users catch up on missed group chat 
  discussions through AI-powered summaries. Uses AWS Lambda, DynamoDB, and 
  supports pluggable AI providers (OpenAI or AWS Bedrock/Claude).

# Global settings applied to all functions
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - arm64
    MemorySize: 128
    # Enable X-Ray tracing for debugging (optional, within free tier)
    Tracing: PassThrough

# Parameters for deployment configuration
Parameters:
  TelegramBotToken:
    Type: String
    Description: Telegram Bot API token from BotFather
    NoEcho: true
  
  OpenAIApiKey:
    Type: String
    Description: OpenAI API key for GPT summarization
    NoEcho: true
    Default: ''
  
  LLMProvider:
    Type: String
    Description: AI provider to use for summarization
    Default: openai
    AllowedValues:
      - openai
      - bedrock
  
  MessageTTLHours:
    Type: Number
    Description: Hours to retain messages before automatic deletion
    Default: 72
    MinValue: 1
    MaxValue: 168
  
  DefaultSummaryHours:
    Type: Number
    Description: Default time window for summary command (hours)
    Default: 24
    MinValue: 1
    MaxValue: 72
  
  LogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period in days
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30

Resources:
  # Lambda function for processing Telegram webhooks
  # Validates: Requirements 9.1 - Use serverless compute (AWS Lambda)
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-webhook-handler'
      Description: Processes Telegram webhook updates for the Summary Bot
      # Handler points to the bundled output in dist folder
      # Run 'npm run bundle:prod' before 'sam build' to generate the bundle
      Handler: handler.handler
      CodeUri: dist/
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref MessagesTable
          # DYNAMODB_ENDPOINT is empty in production (uses AWS DynamoDB)
          # Override via env.local.json for local testing with DynamoDB Local
          DYNAMODB_ENDPOINT: ''
          LLM_PROVIDER: !Ref LLMProvider
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          OPENAI_API_KEY: !Ref OpenAIApiKey
          MESSAGE_TTL_HOURS: !Ref MessageTTLHours
          DEFAULT_SUMMARY_HOURS: !Ref DefaultSummaryHours
      # IAM policies with least privilege
      # Validates: Requirements 7.2 - Use IAM roles with least-privilege permissions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        # Bedrock policy (only needed if using Bedrock provider)
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: 
                - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
                - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-instant-v1'
                - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-v2'
      # HTTP API Gateway event trigger
      # Validates: Requirements 9.3 - Use API Gateway for webhook handling
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: POST
            ApiId: !Ref TelegramBotApi

  # HTTP API Gateway for webhook endpoint
  # Validates: Requirements 9.3 - Use API Gateway (HTTP API is 70% cheaper than REST API)
  TelegramBotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Description: HTTP API for Telegram Bot webhook
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
        AllowHeaders:
          - Content-Type

  # DynamoDB table for message storage
  # Validates: Requirements 9.2 - Use DynamoDB with TTL to minimize storage costs
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-messages'
      # On-demand capacity for cost efficiency with low traffic
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      # TTL for automatic message cleanup
      # Validates: Requirements 2.3, 2.4 - TTL auto-cleanup
      TimeToLiveSpecification:
        AttributeName: expireAt
        Enabled: true
      # Point-in-time recovery disabled to stay within free tier
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      # Server-side encryption (enabled by default, no additional cost)
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Application
          Value: TelegramSummaryBot
        - Key: Environment
          Value: !Ref AWS::StackName

  # CloudWatch Log Group with retention policy
  # Validates: Cost Optimization - Set log retention to 7 days
  TelegramBotFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${TelegramBotFunction}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Application
          Value: TelegramSummaryBot

# Stack outputs for deployment information
Outputs:
  WebhookUrl:
    Description: Webhook URL to register with Telegram BotFather
    Value: !Sub 'https://${TelegramBotApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhook'
  
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt TelegramBotFunction.Arn
  
  FunctionName:
    Description: Lambda function name
    Value: !Ref TelegramBotFunction
  
  MessagesTableName:
    Description: DynamoDB table name for messages
    Value: !Ref MessagesTable
  
  MessagesTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt MessagesTable.Arn
  
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub 'https://${TelegramBotApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
